version: '3'

name: demo

networks:
  app:
    driver: bridge

services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/hughcube/php-demo:base-latest-developer
    ports:
      - "9091:80"
    #user: root:root
    environment:
        HUGHCUBE_ALIFC_ALLOW_FIRE_JOB: On
        COMPOSER_PROXY: ${COMPOSER_PROXY}
    command: /usr/local/bin/php /data/app/artisan serve --host=0.0.0.0 --port=80
    volumes:
      - .:/data/app:rw
      - home-volume:/root/:rw
    restart: always
    networks:
      - app

volumes:
  home-volume: {}
