version: '3'

name: demo

networks:
  app:
    driver: bridge

services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/hughcube/php-demo:base-latest-developer
    container_name: demo-app
    ports:
      - "9091:9000"
    #user: root:root
    environment:
        HUGHCUBE_ALIFC_ALLOW_FIRE_JOB: On
    volumes:
      - .:/data/app:rw
      - .docker/apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:r
      - .docker/php/php.ini-development:/usr/local/etc/php/php.ini:r
      - home-volume:/var/www/:rw
    restart: always
    networks:
      - app

volumes:
  home-volume: {}
