ARG BASE_IMAGE=registry.cn-hangzhou.aliyuncs.com/hughcube/php-demo:base-latest

#########################################################################################################
#### 构建镜像
#########################################################################################################
FROM ${BASE_IMAGE}

ARG COMPOSER_VERSION="2.7.2"

RUN set -eux; \
    #
    # Disable Zend OpCache
    rm -rf /tmp/opcache && mkdir -p /tmp/opcache && chmod -R 0777 /tmp/opcache; \
    rm -rf /usr/local/etc/php/conf.d/*opcache.ini && touch /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini; \
    { \
        echo "zend_extension=opcache"; \
        echo "opcache.enable=0"; \
        echo "opcache.enable_cli=0"; \
    } > /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini; \
    #
    # Update
    apk update; \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS; \
    #
    # Install git
    apk add --no-cache git; \
    #
    # Install subversion
    apk add --no-cache subversion; \
    #
    # Install Zip ext
    apk add --no-cache libzip-dev; \
    apk add --no-cache --virtual .build-deps-ext-zip zlib-dev; \
    docker-php-ext-install zip; \
    apk del --no-network .build-deps-ext-zip; \
    #
    # Install Composer
    if [ -n "$COMPOSER_VERSION" ]; then \
        curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version="$COMPOSER_VERSION"; \
    else \
        curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer; \
    fi; \
    chmod +x /usr/bin/composer; \
    #
    # Clear \
    #pecl clear-cache && \
    rm -rf "/tmp/opcache/*" && \
    docker-php-source delete && \
    apk del --no-network .build-deps

CMD /usr/bin/composer
